; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
;platform = raspberrypi
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino

lib_deps = 
    https://github.com/adafruit/Adafruit_VL53L0X.git
    https://github.com/jrowberg/i2cdevlib.git
    https://github.com/arduino-libraries/MadgwickAHRS.git

board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

; You may need to specifiy the correct COM port if there are several candidates
;upload_port = COM11

monitor_speed = 115200


; Pokud máš debugger (Picoprobe, J-Link, CMSIS-DAP):+
;debug_tool = picoprobe
;debug_port = /dev/tty.usbmodem11201


